import MainProvider from "@/providers/MainProvider"
import "./globals.scss"
import type { Metadata } from "next"
import { Inter } from "next/font/google"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Boronilov Cinema",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <MainProvider>
        <body className={inter.className}>{children}</body>
      </MainProvider>
    </html>
  )
}
